source 'https://github.com/jaccty/MXSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'MXSpecialKit_Example' do
  pod 'MXSpecialKit', :path => '../'

  target 'MXSpecialKit_Tests' do
    inherit! :search_paths

    
  end
end
